name: Node.js Package

on:
  release:
    types: [created]
  repository_dispatch:
    types: [openapi_spec_updated]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@infinity.health'

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun package
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Bump package version
        run: |
          npm version patch -m "chore: bump version to %s"
          git push

      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@infinityhealth"

      - name: Publish to GitHub Package Registry
        run: |
          STREAM_NAME="${{ github.event.client_payload.stream }}"
          npm publish --tag $STREAM_NAME
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
