name: Node.js Package

on:
  repository_dispatch:
    types: [openapi_spec_updated]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@infinity.health'

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAPI_URL: ${{ github.event.client_payload.openapi_url }}

      - name: Bump package version and append commit message with URL
        run: |
          STREAM_NAME="${{ github.event.client_payload.stream }}"
          COMMIT_MESSAGE="${{ github.event.client_payload.commit_message }}"
          COMMIT_URL="${{ github.event.client_payload.commit_url }}"

          # Bump version without committing
          npm version patch --no-git-tag-version

          # Stage the updated package.json
          git add package.json

          # Create the initial version commit
          git commit -m "chore: bump version"

          # Amend the commit with the detailed message
          git commit --amend -m "chore: bump version to $(git describe --tags --abbrev=0)

          $COMMIT_MESSAGE

          See the commit: $COMMIT_URL"

      - name: Bump package version and append commit message
        run: |
          STREAM_NAME="${{ github.event.client_payload.stream }}"
          COMMIT_MESSAGE="${{ github.event.client_payload.commit_message }}"

      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@infinityhealth"

      - name: Publish to GitHub Package Registry
        run: |
          STREAM_NAME="${{ github.event.client_payload.stream }}"
          npm publish --tag $STREAM_NAME
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create and push git tag
        run: |
          STREAM_NAME="${{ github.event.client_payload.stream }}"
          GIT_TAG=$(date +'%Y%m%d%H%M%S')-$STREAM_NAME

          git tag $GIT_TAG
          git push origin $GIT_TAG

      - name: Push changes to repo
        run: git push
